setwd("~/Documents/Studying/Rcourse/ExData_Plotting1-master")
data <- read.table("household_power_consumption.txt",sep = ";",header = T,na.strings = "?")
dates <- c("1/2/2007","2/2/2007")
dates <- as.Date(dates,"%d/%m/%Y")
data$Date <- as.Date(data$Date,"%d/%m/%Y")
subdata <- subset(data,data$Date %in% dates)
subdata$DateTime <- as.POSIXct(paste(subdata$Date, subdata$Time))
png("plot4.png",height = 480,width = 480,units = "px")
par(mfrow=c(2,2))
plot(subdata$DateTime, subdata$Global_active_power, xlab = '', ylab = 'Global Active Power', type = 'l')
plot(subdata$DateTime, subdata$Voltage, xlab = 'datetime', ylab = 'Voltage', type = 'l')
plot(subdata$DateTime,subdata$Sub_metering_1,xlab = "",ylab = "Energy sub metering",type = "l")
lines(subdata$DateTime,subdata$Sub_metering_2,col="red")
lines(subdata$DateTime, subdata$Sub_metering_3, col = 'blue')
legend("topright",col = c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lwd = 1)
plot(subdata$DateTime, subdata$Global_reactive_power, xlab = 'datetime', ylab = 'Global_reactive_power', type = 'l')
dev.off()