setwd("~/Documents/Studying/Rcourse/ExData_Plotting1-master")
data <- read.table("household_power_consumption.txt",sep = ";",header = T,na.strings = "?")
dates <- c("1/2/2007","2/2/2007")
dates <- as.Date(dates,"%d/%m/%Y")
data$Date <- as.Date(data$Date,"%d/%m/%Y")
subdata <- subset(data,data$Date %in% dates)
subdata$DateTime <- as.POSIXct(paste(subdata$Date, subdata$Time))
png("plot2.png",height = 480,width = 480,units = "px")
plot(subdata$DateTime, subdata$Global_active_power, xlab = '', ylab = 'Global Active Power (kilowatt)', type = 'l')
dev.off()